SimpleBusinessManager/Controllers/TotalMensalPorVendedorController.cs
using SimpleBusinessManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBusinessManager.Controllers
{
    [Authorize]
    public class TotalMensalPorVendedorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private string query;

        // GET: TotalMensalPorVendedor
        public ActionResult Index()
        {
            query = "select V2.Nome As Vendedor,DATEPART(month, V1.DataPedido) As Mes,SUM(V1.ValorTotal) As Total from Vendas V1 inner join Vendedors V2 on V1.VendedorId = V2.VendedorId group by V2.Nome, DATEPART(month, V1.DataPedido)";
            return View(db.Database.SqlQuery<SimpleBusinessManager.Relatorios.TotalMensalPorVendedor>(query));
        }
    }
}

SimpleBusinessManager/Controllers/VendedorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SimpleBusinessManager.Models;

namespace SimpleBusinessManager.Controllers
{
    [Authorize]
    public class VendedorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Vendedors
        public ActionResult Index()
        {
            return View(db.Vendedors.ToList());
        }

        // GET: Vendedors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendedor vendedor = db.Vendedors.Find(id);
            if (vendedor == null)
            {
                return HttpNotFound();
            }
            return View(vendedor);
        }

        // GET: Vendedors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vendedors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VendedorId,Nome")] Vendedor vendedor)
        {
            if (ModelState.IsValid)
            {
                db.Vendedors.Add(vendedor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vendedor);
        }

        // GET: Vendedors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendedor vendedor = db.Vendedors.Find(id);
            if (vendedor == null)
            {
                return HttpNotFound();
            }
            return View(vendedor);
        }

        // POST: Vendedors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VendedorId,Nome")] Vendedor vendedor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vendedor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vendedor);
        }

        // GET: Vendedors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vendedor vendedor = db.Vendedors.Find(id);
            if (vendedor == null)
            {
                return HttpNotFound();
            }
            return View(vendedor);
        }

        // POST: Vendedors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vendedor vendedor = db.Vendedors.Find(id);
            db.Vendedors.Remove(vendedor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SimpleBusinessManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SimpleBusinessManager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administração<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Vendedores", "Index", "Vendedors")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                        <li>@Html.ActionLink("Vendas", "Index", "Vendas")</li>
                        <li>@Html.ActionLink("Recebimentos", "Index", "Recebimentos")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Relatórios<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Saldo", "Index", "Saldo")</li>
                                <li>@Html.ActionLink("Total mensal por vendedor", "Index", "TotalMensalPorVendedor")</li>
                            </ul>
                        </li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; Paulo Roberto Elias</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jquerydatatables")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryinputmask")
    @Scripts.Render("~/Scripts/script.js")
    @*@Scripts.Render("~/bundles/fontawesome")*@
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('#Aniversario').val("");
            $('#Telefone').inputmask("(99)99999-9999");
            $('#Celular').inputmask("(99)99999-9999");
            $('#Data').inputmask("99/99/9999");
            $('#DataPedido').inputmask("99/99/9999");
            $('#Valor').inputmask("R$ 999.999,99", { removeMaskOnSubmit: true, numericInput: true });
            $('#ValorTotal').inputmask("R$ 999.999,99", { removeMaskOnSubmit: true, numericInput: true });
        });
    </script>
</body>
</html>